create or replace function public.create_work_request(payload jsonb) returns uuid language plpgsql security definer set search_path=public as $$
declare new_id uuid;skill_value text;initial_stage public.work_stage;
begin if auth.uid() is null then raise exception 'authentication required';end if;initial_stage:=case when coalesce(payload->>'publish','true')::boolean then 'open' else 'draft' end;
 insert into public.work_requests(owner_id,title,description,kind,stage,location_text,urgency_text,cash_budget_cents,visibility,exchange_modes,exchange_summary,constraints,location_visibility)
 values(auth.uid(),trim(payload->>'title'),trim(payload->>'description'),(payload->>'kind')::public.work_kind,initial_stage,nullif(trim(payload->>'location'),''),nullif(trim(payload->>'urgency'),''),nullif(payload->>'cash_budget_cents','')::bigint,case when initial_stage='draft' then 'private' else coalesce(nullif(payload->>'visibility',''),'public') end,array(select jsonb_array_elements_text(coalesce(payload->'exchange_modes','["cash","barter","hybrid"]'::jsonb))::public.exchange_mode),nullif(trim(payload->>'exchange_summary'),''),nullif(trim(payload->>'constraints'),''),coalesce(nullif(payload->>'location_visibility',''),'region')) returning id into new_id;
 for skill_value in select jsonb_array_elements_text(coalesce(payload->'skills','[]'::jsonb)) loop insert into public.work_request_skills(request_id,skill) values(new_id,trim(skill_value)) on conflict do nothing;end loop;return new_id;end $$;

create or replace function public.request_lifecycle_action(target_request_id uuid,expected_version integer,requested_action text) returns uuid language plpgsql security definer set search_path=public as $$
declare r public.work_requests;new_id uuid;
begin select * into r from public.work_requests where id=target_request_id for update;if r.owner_id<>auth.uid() then raise exception 'request not found';end if;if r.version<>expected_version then raise exception 'request changed; refresh';end if;
 if requested_action='publish' then if r.stage<>'draft' then raise exception 'only drafts can be published';end if;update public.work_requests set stage='open',visibility='public',version=version+1,updated_at=now() where id=r.id;
 elsif requested_action='reopen' then if r.stage not in('cancelled','completed') or exists(select 1 from public.work_agreements where request_id=r.id) then raise exception 'request is not eligible to reopen';end if;update public.work_requests set stage='open',visibility='public',version=version+1,updated_at=now() where id=r.id;
 elsif requested_action='duplicate' then insert into public.work_requests(owner_id,title,description,kind,stage,location_text,urgency_text,cash_budget_cents,visibility,exchange_modes,exchange_summary,constraints,location_visibility) select auth.uid(),title||' (copy)',description,kind,'draft',location_text,urgency_text,cash_budget_cents,'private',exchange_modes,exchange_summary,constraints,location_visibility from public.work_requests where id=r.id returning id into new_id;insert into public.work_request_skills(request_id,skill) select new_id,skill from public.work_request_skills where request_id=r.id;return new_id;
 else raise exception 'unsupported lifecycle action';end if;return r.id;end $$;

create or replace function public.revise_trade_offer(target_offer_id uuid,payload jsonb) returns public.trade_offers language plpgsql security definer set search_path=public as $$
declare o public.trade_offers;
begin select * into o from public.trade_offers where id=target_offer_id for update;if o.provider_id<>auth.uid() or o.status<>'pending' then raise exception 'only your pending offer can be revised';end if;
 update public.trade_offers set mode=(payload->>'mode')::public.exchange_mode,scope=trim(payload->>'scope'),exchange_summary=trim(payload->>'exchange_summary'),duration_text=nullif(trim(payload->>'duration'),''),exclusions=nullif(trim(payload->>'exclusions'),''),responsibilities=coalesce(payload->'responsibilities',responsibilities),proposed_milestones=coalesce(payload->'milestones',proposed_milestones),questions=nullif(trim(payload->>'questions'),''),expires_at=nullif(payload->>'expires_at','')::timestamptz,created_at=now() where id=o.id returning * into o;return o;end $$;
create or replace function public.withdraw_trade_offer(target_offer_id uuid) returns void language plpgsql security definer set search_path=public as $$ begin update public.trade_offers set status='withdrawn' where id=target_offer_id and provider_id=auth.uid() and status='pending';if not found then raise exception 'pending offer not found';end if;end $$;

create or replace function public.manage_milestone(target_agreement_id uuid,expected_version integer,action text,payload jsonb) returns public.work_agreements language plpgsql security definer set search_path=public as $$
declare a public.work_agreements;m public.milestones;next_position integer;
begin select * into a from public.work_agreements where id=target_agreement_id for update;if auth.uid() not in(a.requester_id,a.provider_id) then raise exception 'not a participant';end if;if a.version<>expected_version then raise exception 'agreement changed; refresh';end if;if a.status not in('proposed','agreed','scheduled') then raise exception 'planning changes during active work require an agreement amendment';end if;
 if action='add' then select coalesce(max(position),-1)+1 into next_position from public.milestones where agreement_id=a.id;insert into public.milestones(agreement_id,title,position,responsible_profile_id,due_at) values(a.id,trim(payload->>'title'),next_position,nullif(payload->>'responsible_profile_id','')::uuid,nullif(payload->>'due_at','')::timestamptz);
 elsif action='edit' then update public.milestones set title=trim(payload->>'title'),responsible_profile_id=nullif(payload->>'responsible_profile_id','')::uuid,due_at=nullif(payload->>'due_at','')::timestamptz where id=(payload->>'milestone_id')::uuid and agreement_id=a.id;if not found then raise exception 'milestone not found';end if;
 elsif action='remove' then delete from public.milestones where id=(payload->>'milestone_id')::uuid and agreement_id=a.id and completed_at is null;if not found then raise exception 'incomplete milestone not found';end if;
 elsif action='move' then select * into m from public.milestones where id=(payload->>'milestone_id')::uuid and agreement_id=a.id for update;if m.id is null then raise exception 'milestone not found';end if;update public.milestones set position=(payload->>'position')::integer where id=m.id;
 else raise exception 'unsupported milestone action';end if;update public.work_agreements set version=version+1 where id=a.id returning * into a;return a;end $$;

revoke all on function public.request_lifecycle_action(uuid,integer,text),public.revise_trade_offer(uuid,jsonb),public.withdraw_trade_offer(uuid),public.manage_milestone(uuid,integer,text,jsonb) from public;grant execute on function public.request_lifecycle_action(uuid,integer,text),public.revise_trade_offer(uuid,jsonb),public.withdraw_trade_offer(uuid),public.manage_milestone(uuid,integer,text,jsonb) to authenticated;
