create table public.agreement_ledger_items(
 id uuid primary key default gen_random_uuid(),agreement_id uuid not null references public.work_agreements(id) on delete cascade,
 created_by uuid not null references public.profiles(id),item_type text not null check(item_type in('material','tool','rental','permit','delivery','expense','service','other')),
 description text not null check(char_length(description)between 2 and 500),responsibility text not null check(responsibility in('requester','provider','shared','third_party')),
 contribution_mode text not null check(contribution_mode in('cash','barter','included')),quantity_estimate numeric(12,3),quantity_actual numeric(12,3),unit text not null default '',
 estimated_cost_cents bigint check(estimated_cost_cents is null or estimated_cost_cents>=0),actual_cost_cents bigint check(actual_cost_cents is null or actual_cost_cents>=0),
 status text not null default 'needed' check(status in('available','needed','ordered','ready','used','cancelled')),barter_description text not null default '',
 receipt_path text,dependency_hold_id uuid references public.dependency_holds(id) on delete set null,version integer not null default 1,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table public.agreement_ledger_approvals(item_id uuid not null references public.agreement_ledger_items(id) on delete cascade,profile_id uuid not null references public.profiles(id),version integer not null,approved_at timestamptz not null default now(),primary key(item_id,profile_id));
alter table public.agreement_ledger_items enable row level security;alter table public.agreement_ledger_approvals enable row level security;
create policy "participants read ledger" on public.agreement_ledger_items for select using(exists(select 1 from public.work_agreements a where a.id=agreement_id and auth.uid()in(a.requester_id,a.provider_id)));
create policy "participants read ledger approvals" on public.agreement_ledger_approvals for select using(exists(select 1 from public.agreement_ledger_items i join public.work_agreements a on a.id=i.agreement_id where i.id=item_id and auth.uid()in(a.requester_id,a.provider_id)));

create or replace function public.get_agreement_ledger(target_agreement_id uuid)returns jsonb language plpgsql stable security definer set search_path=public as $$declare a public.work_agreements;begin
 select * into a from public.work_agreements where id=target_agreement_id;if auth.uid()not in(a.requester_id,a.provider_id)then raise exception'agreement participant required';end if;
 return jsonb_build_object('items',coalesce((select jsonb_agg(to_jsonb(i)||jsonb_build_object('approvals',coalesce((select jsonb_agg(to_jsonb(ap))from public.agreement_ledger_approvals ap where ap.item_id=i.id),'[]'::jsonb))order by i.created_at)from public.agreement_ledger_items i where i.agreement_id=a.id),'[]'::jsonb),'summary',jsonb_build_object('needed',(select count(*)from public.agreement_ledger_items where agreement_id=a.id and status in('needed','ordered')),'ready',(select count(*)from public.agreement_ledger_items where agreement_id=a.id and status in('available','ready','used')),'estimated_cash_cents',(select coalesce(sum(estimated_cost_cents),0)from public.agreement_ledger_items where agreement_id=a.id and contribution_mode='cash'and status<>'cancelled'),'actual_cash_cents',(select coalesce(sum(actual_cost_cents),0)from public.agreement_ledger_items where agreement_id=a.id and contribution_mode='cash'and status<>'cancelled')));end$$;
create or replace function public.save_ledger_item(target_agreement_id uuid,target_item_id uuid,payload jsonb)returns uuid language plpgsql security definer set search_path=public as $$declare a public.work_agreements;result uuid;begin
 select * into a from public.work_agreements where id=target_agreement_id;if auth.uid()not in(a.requester_id,a.provider_id)or a.status in('completed','cancelled')then raise exception'editable agreement participant required';end if;
 if target_item_id is null then insert into public.agreement_ledger_items(agreement_id,created_by,item_type,description,responsibility,contribution_mode,quantity_estimate,unit,estimated_cost_cents,barter_description,status)values(a.id,auth.uid(),payload->>'item_type',trim(payload->>'description'),payload->>'responsibility',payload->>'contribution_mode',nullif(payload->>'quantity','')::numeric,coalesce(payload->>'unit',''),nullif(payload->>'estimated_cost_cents','')::bigint,coalesce(payload->>'barter_description',''),coalesce(payload->>'status','needed'))returning id into result;
 else update public.agreement_ledger_items set item_type=coalesce(payload->>'item_type',item_type),description=coalesce(nullif(trim(payload->>'description'),''),description),responsibility=coalesce(payload->>'responsibility',responsibility),contribution_mode=coalesce(payload->>'contribution_mode',contribution_mode),quantity_estimate=coalesce(nullif(payload->>'quantity','')::numeric,quantity_estimate),unit=coalesce(payload->>'unit',unit),estimated_cost_cents=coalesce(nullif(payload->>'estimated_cost_cents','')::bigint,estimated_cost_cents),barter_description=coalesce(payload->>'barter_description',barter_description),version=version+1,updated_at=now()where id=target_item_id and agreement_id=a.id returning id into result;delete from public.agreement_ledger_approvals where item_id=result;end if;return result;end$$;
create or replace function public.manage_ledger_item(target_item_id uuid,item_action text,payload jsonb default'{}'::jsonb)returns void language plpgsql security definer set search_path=public as $$declare i public.agreement_ledger_items;a public.work_agreements;approval_count int;begin
 select * into i from public.agreement_ledger_items where id=target_item_id for update;select * into a from public.work_agreements where id=i.agreement_id;if auth.uid()not in(a.requester_id,a.provider_id)then raise exception'agreement participant required';end if;
 if item_action='approve'then insert into public.agreement_ledger_approvals(item_id,profile_id,version)values(i.id,auth.uid(),i.version)on conflict(item_id,profile_id)do update set version=excluded.version,approved_at=now();
 elsif item_action='status'then update public.agreement_ledger_items set status=payload->>'status',quantity_actual=nullif(payload->>'quantity_actual','')::numeric,actual_cost_cents=nullif(payload->>'actual_cost_cents','')::bigint,updated_at=now()where id=i.id;
 elsif item_action='receipt'then update public.agreement_ledger_items set receipt_path=payload->>'receipt_path',updated_at=now()where id=i.id;
 elsif item_action='dependency'then update public.agreement_ledger_items set dependency_hold_id=nullif(payload->>'hold_id','')::uuid,updated_at=now()where id=i.id;else raise exception'invalid ledger action';end if;
 select count(*)into approval_count from public.agreement_ledger_approvals where item_id=i.id and version=i.version;if i.responsibility='shared'and approval_count=2 then perform public.notify_user(i.created_by,'agreement','Shared cost approved','Both participants approved '||i.description||'.');end if;end$$;
revoke all on function public.get_agreement_ledger(uuid),public.save_ledger_item(uuid,uuid,jsonb),public.manage_ledger_item(uuid,text,jsonb)from public;grant execute on function public.get_agreement_ledger(uuid),public.save_ledger_item(uuid,uuid,jsonb),public.manage_ledger_item(uuid,text,jsonb)to authenticated;
