alter table public.circles add column if not exists rules text not null default '';
alter table public.work_requests add column if not exists circle_id uuid references public.circles(id) on delete set null;
alter table public.work_requests add constraint circle_visibility_requires_circle check((visibility='circle')=(circle_id is not null));
create table public.circle_resources(id uuid primary key default gen_random_uuid(),circle_id uuid not null references public.circles(id) on delete cascade,owner_id uuid not null references public.profiles(id),kind text not null check(kind in('tool','equipment','workspace','vehicle','material','access','other')),name text not null check(char_length(name) between 2 and 120),description text not null default '',availability_text text not null default '',created_at timestamptz not null default now());
alter table public.circle_resources enable row level security;grant select on public.circle_resources to authenticated;
create policy "active members read circle resources" on public.circle_resources for select using(exists(select 1 from public.circle_members m where m.circle_id=circle_id and m.profile_id=auth.uid() and m.status='active'));

drop policy if exists "public circles readable" on public.circles;
create policy "visible circles readable" on public.circles for select using(visibility='public' or owner_id=auth.uid() or exists(select 1 from public.circle_members m where m.circle_id=id and m.profile_id=auth.uid()));
drop policy if exists "circle membership readable" on public.circle_members;
create policy "circle membership scoped read" on public.circle_members for select using(profile_id=auth.uid() or exists(select 1 from public.circle_members mine where mine.circle_id=circle_id and mine.profile_id=auth.uid() and mine.status='active'));
drop policy if exists "visible requests readable" on public.work_requests;
create policy "visible requests readable" on public.work_requests for select using(visibility='public' or owner_id=auth.uid() or(visibility='circle' and exists(select 1 from public.circle_members m where m.circle_id=work_requests.circle_id and m.profile_id=auth.uid() and m.status='active')));
drop policy if exists "request skills readable" on public.work_request_skills;
create policy "request skills readable" on public.work_request_skills for select using(exists(select 1 from public.work_requests r where r.id=request_id and(r.visibility='public' or r.owner_id=auth.uid() or(r.visibility='circle' and exists(select 1 from public.circle_members m where m.circle_id=r.circle_id and m.profile_id=auth.uid() and m.status='active')))));

create or replace function public.create_circle(circle_name text,circle_description text,circle_visibility text,circle_rules text) returns uuid language plpgsql security definer set search_path=public as $$declare new_id uuid;begin if auth.uid() is null then raise exception 'authentication required';end if;if circle_visibility not in('public','private')then raise exception 'invalid visibility';end if;insert into public.circles(owner_id,name,description,visibility,rules)values(auth.uid(),trim(circle_name),trim(circle_description),circle_visibility,coalesce(circle_rules,''))returning id into new_id;insert into public.circle_members(circle_id,profile_id,role,status)values(new_id,auth.uid(),'owner','active');return new_id;end$$;
create or replace function public.request_circle_membership(target_circle_id uuid) returns void language plpgsql security definer set search_path=public as $$declare c public.circles;begin select * into c from public.circles where id=target_circle_id;if c.id is null then raise exception 'circle unavailable';end if;insert into public.circle_members(circle_id,profile_id,role,status)values(c.id,auth.uid(),'member','requested')on conflict(circle_id,profile_id)do update set status='requested' where circle_members.status in('removed');perform public.notify_user(c.owner_id,'network','Circle membership request',(select display_name from public.profiles where id=auth.uid())||' asked to join '||c.name||'.');end$$;
create or replace function public.invite_circle_member(target_circle_id uuid,target_profile_id uuid) returns void language plpgsql security definer set search_path=public as $$begin if not exists(select 1 from public.circle_members where circle_id=target_circle_id and profile_id=auth.uid() and status='active' and role in('owner','moderator'))then raise exception 'circle moderator required';end if;insert into public.circle_members(circle_id,profile_id,role,status)values(target_circle_id,target_profile_id,'member','invited')on conflict(circle_id,profile_id)do update set status='invited' where circle_members.status in('removed');perform public.notify_user(target_profile_id,'network','Circle invitation','You were invited to '||(select name from public.circles where id=target_circle_id)||'.');end$$;
create or replace function public.manage_circle_membership(target_circle_id uuid,target_profile_id uuid,member_action text,new_role text default null) returns void language plpgsql security definer set search_path=public as $$declare mine public.circle_members;target public.circle_members;c public.circles;begin select * into mine from public.circle_members where circle_id=target_circle_id and profile_id=auth.uid();select * into target from public.circle_members where circle_id=target_circle_id and profile_id=target_profile_id for update;select * into c from public.circles where id=target_circle_id;
 if member_action='accept' and target_profile_id=auth.uid() and target.status='invited'then update public.circle_members set status='active',joined_at=now()where circle_id=target_circle_id and profile_id=auth.uid();
 elsif member_action='decline' and target_profile_id=auth.uid() and target.status='invited'then update public.circle_members set status='removed'where circle_id=target_circle_id and profile_id=auth.uid();
 elsif member_action='leave' and target_profile_id=auth.uid() and mine.role<>'owner'then update public.circle_members set status='removed'where circle_id=target_circle_id and profile_id=auth.uid();
 elsif mine.status='active' and mine.role in('owner','moderator') and member_action='approve' and target.status='requested'then update public.circle_members set status='active',joined_at=now()where circle_id=target_circle_id and profile_id=target_profile_id;
 elsif mine.status='active' and mine.role in('owner','moderator') and member_action in('decline','remove') and target.role<>'owner'then update public.circle_members set status='removed'where circle_id=target_circle_id and profile_id=target_profile_id;
 elsif mine.role='owner' and member_action='role' and new_role in('member','moderator') and target.role<>'owner'then update public.circle_members set role=new_role where circle_id=target_circle_id and profile_id=target_profile_id;
 else raise exception 'membership action unavailable';end if;perform public.notify_user(target_profile_id,'network','Circle membership updated','Your membership in '||c.name||' is now '||(select status from public.circle_members where circle_id=target_circle_id and profile_id=target_profile_id)||'.');end$$;
create or replace function public.save_circle_resource(target_circle_id uuid,resource_id uuid,payload jsonb) returns uuid language plpgsql security definer set search_path=public as $$declare result_id uuid;begin if not exists(select 1 from public.circle_members where circle_id=target_circle_id and profile_id=auth.uid() and status='active')then raise exception 'active circle membership required';end if;if resource_id is null then insert into public.circle_resources(circle_id,owner_id,kind,name,description,availability_text)values(target_circle_id,auth.uid(),payload->>'kind',trim(payload->>'name'),coalesce(payload->>'description',''),coalesce(payload->>'availability',''))returning id into result_id;else update public.circle_resources set kind=payload->>'kind',name=trim(payload->>'name'),description=coalesce(payload->>'description',''),availability_text=coalesce(payload->>'availability','')where id=resource_id and owner_id=auth.uid() returning id into result_id;end if;if result_id is null then raise exception 'resource unavailable';end if;return result_id;end$$;
create or replace function public.delete_circle_resource(target_resource_id uuid) returns void language plpgsql security definer set search_path=public as $$begin delete from public.circle_resources r where r.id=target_resource_id and(r.owner_id=auth.uid()or exists(select 1 from public.circle_members m where m.circle_id=r.circle_id and m.profile_id=auth.uid()and m.status='active'and m.role in('owner','moderator')));if not found then raise exception 'resource unavailable';end if;end$$;
create or replace function public.create_circle_request(target_circle_id uuid,payload jsonb) returns uuid language plpgsql security definer set search_path=public as $$declare new_id uuid;skill text;begin if not exists(select 1 from public.circle_members where circle_id=target_circle_id and profile_id=auth.uid()and status='active')then raise exception 'active membership required';end if;insert into public.work_requests(owner_id,title,description,kind,stage,location_text,urgency_text,cash_budget_cents,visibility,exchange_modes,exchange_summary,constraints,location_visibility,circle_id)values(auth.uid(),trim(payload->>'title'),trim(payload->>'description'),(payload->>'kind')::public.work_kind,case when coalesce((payload->>'publish')::boolean,true)then'open'::public.work_stage else'draft'::public.work_stage end,payload->>'location',payload->>'urgency',nullif(payload->>'cash_budget_cents','')::bigint,'circle',coalesce(array(select jsonb_array_elements_text(payload->'exchange_modes'))::public.exchange_mode[],array['barter'::public.exchange_mode]),payload->>'exchange_summary',payload->>'constraints','participants',target_circle_id)returning id into new_id;for skill in select jsonb_array_elements_text(coalesce(payload->'skills','[]'::jsonb))loop insert into public.work_request_skills(request_id,skill)values(new_id,skill);end loop;return new_id;end$$;

create or replace function public.get_circle_hub() returns jsonb language sql stable security definer set search_path=public as $$select jsonb_build_object('circles',coalesce((select jsonb_agg(to_jsonb(c)||jsonb_build_object('membership',to_jsonb(m),'member_count',(select count(*)from public.circle_members cm where cm.circle_id=c.id and cm.status='active'),'request_count',(select count(*)from public.work_requests wr where wr.circle_id=c.id and wr.stage='open'))order by c.created_at desc)from public.circles c left join public.circle_members m on m.circle_id=c.id and m.profile_id=auth.uid()where c.visibility='public'or m.profile_id is not null),'[]'::jsonb),'members',coalesce((select jsonb_agg(to_jsonb(m)||jsonb_build_object('display_name',p.display_name,'completed_inside',(select count(*)from public.work_agreements a join public.work_requests r on r.id=a.request_id where r.circle_id=m.circle_id and a.status='completed'and p.id in(a.requester_id,a.provider_id)))order by m.joined_at)from public.circle_members m join public.profiles p on p.id=m.profile_id where exists(select 1 from public.circle_members mine where mine.circle_id=m.circle_id and mine.profile_id=auth.uid()and mine.status='active')),'[]'::jsonb),'resources',coalesce((select jsonb_agg(to_jsonb(r)||jsonb_build_object('owner_name',p.display_name)order by r.created_at desc)from public.circle_resources r join public.profiles p on p.id=r.owner_id where exists(select 1 from public.circle_members mine where mine.circle_id=r.circle_id and mine.profile_id=auth.uid()and mine.status='active')),'[]'::jsonb),'requests',coalesce((select jsonb_agg(to_jsonb(w)||jsonb_build_object('owner_name',p.display_name,'skills',coalesce((select jsonb_agg(skill)from public.work_request_skills s where s.request_id=w.id),'[]'::jsonb))order by w.created_at desc)from public.work_requests w join public.profiles p on p.id=w.owner_id where w.visibility='circle'and exists(select 1 from public.circle_members mine where mine.circle_id=w.circle_id and mine.profile_id=auth.uid()and mine.status='active')),'[]'::jsonb))$$;
revoke all on function public.create_circle(text,text,text,text),public.request_circle_membership(uuid),public.invite_circle_member(uuid,uuid),public.manage_circle_membership(uuid,uuid,text,text),public.save_circle_resource(uuid,uuid,jsonb),public.delete_circle_resource(uuid),public.create_circle_request(uuid,jsonb),public.get_circle_hub() from public;
grant execute on function public.create_circle(text,text,text,text),public.request_circle_membership(uuid),public.invite_circle_member(uuid,uuid),public.manage_circle_membership(uuid,uuid,text,text),public.save_circle_resource(uuid,uuid,jsonb),public.delete_circle_resource(uuid),public.create_circle_request(uuid,jsonb),public.get_circle_hub() to authenticated;
