alter table public.collaboration_invitations drop constraint if exists collaboration_invitations_status_check;
alter table public.collaboration_invitations add constraint collaboration_invitations_status_check check(status in('pending','accepted','declined','muted','archived','converted'));
alter table public.collaboration_invitations add column converted_request_id uuid references public.work_requests(id) on delete set null;

create table public.introduction_workspaces(
 invitation_id uuid primary key references public.collaboration_invitations(id) on delete cascade,
 scope text not null default '', responsibilities jsonb not null default '{}'::jsonb, materials text not null default '', exclusions text not null default '',
 exchange_terms text not null default '', proposed_windows text not null default '', timezone text not null default 'America/New_York',
 version integer not null default 1, updated_by uuid not null references public.profiles(id), updated_at timestamptz not null default now(),
 sender_confirmed_version integer, recipient_confirmed_version integer
);
alter table public.introduction_workspaces enable row level security;
create policy "accepted invitation participants read workspace" on public.introduction_workspaces for select using(exists(select 1 from public.collaboration_invitations i where i.id=invitation_id and auth.uid() in(i.sender_id,i.recipient_id)));
grant select on public.introduction_workspaces to authenticated;

create or replace function public.update_introduction_workspace(target_invitation_id uuid,expected_version integer,payload jsonb) returns public.introduction_workspaces language plpgsql security definer set search_path=public as $$declare i public.collaboration_invitations;w public.introduction_workspaces;begin
 select * into i from public.collaboration_invitations where id=target_invitation_id for update;if i.status<>'accepted' or auth.uid() not in(i.sender_id,i.recipient_id) then raise exception 'accepted invitation participant required';end if;
 insert into public.introduction_workspaces(invitation_id,updated_by) values(i.id,auth.uid()) on conflict do nothing;select * into w from public.introduction_workspaces where invitation_id=i.id for update;if w.version<>expected_version then raise exception 'workspace changed; reload current terms';end if;
 update public.introduction_workspaces set scope=coalesce(payload->>'scope',scope),responsibilities=coalesce(payload->'responsibilities',responsibilities),materials=coalesce(payload->>'materials',materials),exclusions=coalesce(payload->>'exclusions',exclusions),exchange_terms=coalesce(payload->>'exchange_terms',exchange_terms),proposed_windows=coalesce(payload->>'proposed_windows',proposed_windows),timezone=coalesce(payload->>'timezone',timezone),version=version+1,updated_by=auth.uid(),updated_at=now(),sender_confirmed_version=null,recipient_confirmed_version=null where invitation_id=i.id returning * into w;
 perform public.notify_user(case when auth.uid()=i.sender_id then i.recipient_id else i.sender_id end,'network','Collaboration terms updated',(select display_name from public.profiles where id=auth.uid())||' updated the shared planning workspace.');return w;end$$;
create or replace function public.confirm_introduction_workspace(target_invitation_id uuid,expected_version integer) returns public.introduction_workspaces language plpgsql security definer set search_path=public as $$declare i public.collaboration_invitations;w public.introduction_workspaces;begin select * into i from public.collaboration_invitations where id=target_invitation_id;select * into w from public.introduction_workspaces where invitation_id=i.id for update;if i.status<>'accepted' or auth.uid() not in(i.sender_id,i.recipient_id) or w.version<>expected_version then raise exception 'current accepted workspace required';end if;update public.introduction_workspaces set sender_confirmed_version=case when auth.uid()=i.sender_id then version else sender_confirmed_version end,recipient_confirmed_version=case when auth.uid()=i.recipient_id then version else recipient_confirmed_version end where invitation_id=i.id returning * into w;return w;end$$;
create or replace function public.convert_introduction_to_request(target_invitation_id uuid) returns uuid language plpgsql security definer set search_path=public as $$declare i public.collaboration_invitations;w public.introduction_workspaces;new_id uuid;begin select * into i from public.collaboration_invitations where id=target_invitation_id for update;select * into w from public.introduction_workspaces where invitation_id=i.id;if i.status<>'accepted' or auth.uid() not in(i.sender_id,i.recipient_id) or w.sender_confirmed_version<>w.version or w.recipient_confirmed_version<>w.version then raise exception 'both participants must confirm current terms';end if;insert into public.work_requests(owner_id,title,description,kind,stage,visibility,exchange_modes,exchange_summary,constraints,location_visibility) values(auth.uid(),left('Collaboration: '||coalesce(nullif(w.scope,''),i.need_text),140),coalesce(nullif(w.scope,''),i.need_text),'other','draft','private',array['barter'::public.exchange_mode,'hybrid'::public.exchange_mode],w.exchange_terms,concat_ws(E'\n',nullif(w.materials,''),nullif(w.exclusions,'')),'participants') returning id into new_id;update public.collaboration_invitations set status='converted',converted_request_id=new_id where id=i.id;perform public.notify_user(case when auth.uid()=i.sender_id then i.recipient_id else i.sender_id end,'network','Collaboration moved to work','A mutually confirmed introduction was converted into a private draft.',new_id,null);return new_id;end$$;
create or replace function public.manage_network_item(item_kind text,target_id uuid,action text) returns void language plpgsql security definer set search_path=public as $$declare other_id uuid;begin
 if item_kind='invitation' and action='archive' then update public.collaboration_invitations set status='archived' where id=target_id and auth.uid() in(sender_id,recipient_id) and status in('declined','muted','accepted');if not found then raise exception 'invitation cannot be archived';end if;
 elsif item_kind='search' and action='delete' then delete from public.saved_searches where id=target_id and owner_id=auth.uid();
 elsif item_kind='profile' and action='block' then select case when sender_id=auth.uid() then recipient_id else sender_id end into other_id from public.collaboration_invitations where id=target_id and auth.uid() in(sender_id,recipient_id);if other_id is null then raise exception 'invitation participant required';end if;insert into public.blocks(blocker_id,blocked_id) values(auth.uid(),other_id) on conflict do nothing;update public.collaboration_invitations set status='muted' where id=target_id and status in('pending','accepted');
 elsif item_kind='profile' and action='report' then select case when sender_id=auth.uid() then recipient_id else sender_id end into other_id from public.collaboration_invitations where id=target_id and auth.uid() in(sender_id,recipient_id);insert into public.safety_reports(reporter_id,reported_profile_id,reason,detail) values(auth.uid(),other_id,'Introduction concern','Reported from collaboration introduction');else raise exception 'unsupported network action';end if;end$$;

create or replace function public.send_collaboration_invitation(target_profile_id uuid,need_value text,offer_value text,note_value text default null,target_request_id uuid default null) returns uuid language plpgsql security definer set search_path=public as $$declare new_id uuid;begin
 if auth.uid() is null or target_profile_id=auth.uid() then raise exception 'valid signed-in recipient required';end if;if exists(select 1 from public.blocks where(blocker_id=target_profile_id and blocked_id=auth.uid())or(blocker_id=auth.uid() and blocked_id=target_profile_id))then raise exception 'interaction unavailable';end if;
 if (select count(*) from public.collaboration_invitations where sender_id=auth.uid() and created_at>now()-interval '24 hours')>=10 then raise exception 'daily invitation limit reached';end if;
 if exists(select 1 from public.collaboration_invitations where sender_id=auth.uid() and recipient_id=target_profile_id and status in('declined','muted') and responded_at>now()-interval '30 days')then raise exception 'this person is not accepting another invitation';end if;
 insert into public.collaboration_invitations(sender_id,recipient_id,request_id,need_text,offer_text,note)values(auth.uid(),target_profile_id,target_request_id,trim(need_value),trim(offer_value),nullif(trim(note_value),''))returning id into new_id;perform public.notify_user(target_profile_id,'network','New collaboration invitation',(select display_name from public.profiles where id=auth.uid())||' proposed a possible exchange.',target_request_id,null);return new_id;end$$;

create or replace function public.get_network_inbox() returns jsonb language sql stable security definer set search_path=public as $$select jsonb_build_object('invitations',coalesce((select jsonb_agg((to_jsonb(i)||jsonb_build_object('sender_name',s.display_name,'recipient_name',r.display_name,'workspace',to_jsonb(w)))order by i.created_at desc)from public.collaboration_invitations i join public.profiles s on s.id=i.sender_id join public.profiles r on r.id=i.recipient_id left join public.introduction_workspaces w on w.invitation_id=i.id where auth.uid()in(i.sender_id,i.recipient_id)),'[]'::jsonb),'messages',coalesce((select jsonb_agg((to_jsonb(m)||jsonb_build_object('author_name',p.display_name))order by m.created_at)from public.introduction_messages m join public.profiles p on p.id=m.author_id join public.collaboration_invitations i on i.id=m.invitation_id where i.status in('accepted','converted')and auth.uid()in(i.sender_id,i.recipient_id)),'[]'::jsonb),'saved_profiles',coalesce((select jsonb_agg(profile_id)from public.saved_profiles where owner_id=auth.uid()),'[]'::jsonb),'saved_searches',coalesce((select jsonb_agg(to_jsonb(x)order by created_at desc)from public.saved_searches x where owner_id=auth.uid()),'[]'::jsonb))$$;
revoke all on function public.update_introduction_workspace(uuid,integer,jsonb),public.confirm_introduction_workspace(uuid,integer),public.convert_introduction_to_request(uuid),public.manage_network_item(text,uuid,text) from public;
grant execute on function public.update_introduction_workspace(uuid,integer,jsonb),public.confirm_introduction_workspace(uuid,integer),public.convert_introduction_to_request(uuid),public.manage_network_item(text,uuid,text) to authenticated;

create or replace function public.discover_profiles(search_text text default '',exchange_filter text default null,remote_only boolean default false)
returns table(profile jsonb,capabilities jsonb,portfolio jsonb,reviews jsonb) language sql stable security definer set search_path=public as $$
 select (to_jsonb(p)-'deactivated_at')||jsonb_build_object(
  'following',exists(select 1 from public.follows f where f.follower_id=auth.uid() and f.followed_profile_id=p.id),
  'completed_count',(select count(*) from public.work_agreements a where a.status='completed' and p.id in(a.requester_id,a.provider_id)),
  'review_count',(select count(*) from public.work_reviews rv where rv.subject_id=p.id),
  'match_score',(
   10*(select count(*) from public.capabilities theirs join public.capabilities mine on mine.profile_id=auth.uid() and mine.direction='need' where theirs.profile_id=p.id and theirs.direction='offer' and lower(theirs.label)=lower(mine.label))+
   8*(select count(*) from public.capabilities theirs join public.capabilities mine on mine.profile_id=auth.uid() and mine.direction='offer' where theirs.profile_id=p.id and theirs.direction='need' and lower(theirs.label)=lower(mine.label))+
   case when p.location_text is not null and p.location_text=(select location_text from public.profiles where id=auth.uid())then 4 else 0 end+
   case when p.remote_available then 2 else 0 end+
   case when p.availability_text is not null and p.availability_text<>'' then 1 else 0 end+
   least(5,(select count(*) from public.portfolio_entries pe where pe.profile_id=p.id and pe.visibility='public'))+
   case when exists(select 1 from public.profiles me where me.id=auth.uid() and me.preferred_exchange_modes&&p.preferred_exchange_modes)then 3 else 0 end
  )) profile,
 coalesce((select jsonb_agg(to_jsonb(c))from public.capabilities c where c.profile_id=p.id),'[]'::jsonb),
 coalesce((select jsonb_agg(to_jsonb(pe)order by pe.published_at desc)from public.portfolio_entries pe where pe.profile_id=p.id and pe.visibility='public'),'[]'::jsonb),
 coalesce((select jsonb_agg(to_jsonb(rv)order by rv.created_at desc)from public.work_reviews rv where rv.subject_id=p.id),'[]'::jsonb)
 from public.profiles p where p.is_active and p.profile_visibility='public' and(not remote_only or p.remote_available)and(exchange_filter is null or exchange_filter::public.exchange_mode=any(p.preferred_exchange_modes))and(coalesce(search_text,'')=''or p.display_name ilike'%'||search_text||'%'or p.bio ilike'%'||search_text||'%'or exists(select 1 from public.capabilities c where c.profile_id=p.id and c.label ilike'%'||search_text||'%'))
 order by ((10*(select count(*) from public.capabilities theirs join public.capabilities mine on mine.profile_id=auth.uid() and mine.direction='need' where theirs.profile_id=p.id and theirs.direction='offer' and lower(theirs.label)=lower(mine.label)))+(8*(select count(*) from public.capabilities theirs join public.capabilities mine on mine.profile_id=auth.uid() and mine.direction='offer' where theirs.profile_id=p.id and theirs.direction='need' and lower(theirs.label)=lower(mine.label)))) desc,p.created_at desc limit 50$$;
grant execute on function public.discover_profiles(text,text,boolean) to anon,authenticated;
