create table public.work_issues(
 id uuid primary key default gen_random_uuid(),agreement_id uuid not null references public.work_agreements(id) on delete cascade,reported_by uuid not null references public.profiles(id),
 category text not null check(category in('hidden_condition','damaged_material','access','weather','safety','scope_discovery','mistake','other')),
 title text not null check(char_length(title)between 3 and 180),detail text not null check(char_length(detail)between 10 and 4000),
 affected_milestone_id uuid references public.milestones(id) on delete set null,affected_obligation_id uuid references public.agreement_obligations(id) on delete set null,
 unaffected_work_can_continue boolean not null default true,status text not null default 'open' check(status in('open','change_proposed','resolved','escalated','closed')),
 created_at timestamptz not null default now(),resolved_at timestamptz
);
create table public.change_orders(
 id uuid primary key default gen_random_uuid(),issue_id uuid not null references public.work_issues(id) on delete cascade,agreement_id uuid not null references public.work_agreements(id) on delete cascade,
 proposed_by uuid not null references public.profiles(id),version integer not null,scope_delta text not null,time_delta_minutes integer not null default 0,
 cash_delta_cents bigint not null default 0,barter_delta text not null default '',schedule_delta text not null default '',status text not null default 'proposed' check(status in('proposed','accepted','declined','superseded')),
 responded_by uuid references public.profiles(id),responded_at timestamptz,created_at timestamptz not null default now()
);
create unique index one_pending_change_order_per_issue on public.change_orders(issue_id)where status='proposed';
create table public.work_issue_evidence(id uuid primary key default gen_random_uuid(),issue_id uuid not null references public.work_issues(id) on delete cascade,uploaded_by uuid not null references public.profiles(id),asset_path text not null,caption text not null default'',created_at timestamptz not null default now());
alter table public.work_issues enable row level security;alter table public.change_orders enable row level security;alter table public.work_issue_evidence enable row level security;
create policy "participants read work issues" on public.work_issues for select using(exists(select 1 from public.work_agreements a where a.id=agreement_id and auth.uid()in(a.requester_id,a.provider_id)));
create policy "participants read change orders" on public.change_orders for select using(exists(select 1 from public.work_agreements a where a.id=agreement_id and auth.uid()in(a.requester_id,a.provider_id)));
create policy "participants read issue evidence" on public.work_issue_evidence for select using(exists(select 1 from public.work_issues i join public.work_agreements a on a.id=i.agreement_id where i.id=issue_id and auth.uid()in(a.requester_id,a.provider_id)));

create or replace function public.get_change_order_hub(target_agreement_id uuid)returns jsonb language plpgsql stable security definer set search_path=public as $$declare a public.work_agreements;begin select*into a from public.work_agreements where id=target_agreement_id;if auth.uid()not in(a.requester_id,a.provider_id)then raise exception'agreement participant required';end if;return jsonb_build_object('issues',coalesce((select jsonb_agg(to_jsonb(i)||jsonb_build_object('reporter_name',p.display_name,'orders',coalesce((select jsonb_agg(to_jsonb(c)order by c.created_at desc)from public.change_orders c where c.issue_id=i.id),'[]'::jsonb),'evidence',coalesce((select jsonb_agg(to_jsonb(e))from public.work_issue_evidence e where e.issue_id=i.id),'[]'::jsonb))order by i.created_at desc)from public.work_issues i join public.profiles p on p.id=i.reported_by where i.agreement_id=a.id),'[]'::jsonb),'baseline',jsonb_build_object('version',a.version,'scope',a.scope_snapshot,'exchange',a.exchange_snapshot,'status',a.status));end$$;
create or replace function public.report_work_issue(target_agreement_id uuid,payload jsonb)returns uuid language plpgsql security definer set search_path=public as $$declare a public.work_agreements;result uuid;other_id uuid;begin select*into a from public.work_agreements where id=target_agreement_id;if auth.uid()not in(a.requester_id,a.provider_id)or a.status not in('scheduled','active','review')then raise exception'active agreement participant required';end if;insert into public.work_issues(agreement_id,reported_by,category,title,detail,affected_milestone_id,affected_obligation_id,unaffected_work_can_continue)values(a.id,auth.uid(),payload->>'category',trim(payload->>'title'),trim(payload->>'detail'),nullif(payload->>'milestone_id','')::uuid,nullif(payload->>'obligation_id','')::uuid,coalesce((payload->>'unaffected_work_can_continue')::boolean,true))returning id into result;other_id:=case when auth.uid()=a.requester_id then a.provider_id else a.requester_id end;perform public.notify_user(other_id,'agreement','Work issue reported','Review the newly documented condition before affected work continues.',a.request_id,a.id);return result;end$$;
create or replace function public.propose_change_order(target_issue_id uuid,payload jsonb)returns uuid language plpgsql security definer set search_path=public as $$declare i public.work_issues;a public.work_agreements;result uuid;other_id uuid;begin select*into i from public.work_issues where id=target_issue_id for update;select*into a from public.work_agreements where id=i.agreement_id;if auth.uid()not in(a.requester_id,a.provider_id)or i.status in('resolved','escalated','closed')then raise exception'open issue participant required';end if;update public.change_orders set status='superseded'where issue_id=i.id and status='proposed';insert into public.change_orders(issue_id,agreement_id,proposed_by,version,scope_delta,time_delta_minutes,cash_delta_cents,barter_delta,schedule_delta)values(i.id,a.id,auth.uid(),a.version+1,trim(payload->>'scope_delta'),coalesce((payload->>'time_delta_minutes')::integer,0),coalesce((payload->>'cash_delta_cents')::bigint,0),coalesce(payload->>'barter_delta',''),coalesce(payload->>'schedule_delta',''))returning id into result;update public.work_issues set status='change_proposed'where id=i.id;other_id:=case when auth.uid()=a.requester_id then a.provider_id else a.requester_id end;perform public.notify_user(other_id,'agreement','Change order proposed','Compare the proposed difference with the accepted baseline.',a.request_id,a.id);return result;end$$;
create or replace function public.respond_change_order(target_change_order_id uuid,accept boolean)returns void language plpgsql security definer set search_path=public as $$declare c public.change_orders;i public.work_issues;a public.work_agreements;begin select*into c from public.change_orders where id=target_change_order_id and status='proposed'for update;select*into i from public.work_issues where id=c.issue_id for update;select*into a from public.work_agreements where id=c.agreement_id for update;if auth.uid()not in(a.requester_id,a.provider_id)or auth.uid()=c.proposed_by then raise exception'counterparty response required';end if;update public.change_orders set status=case when accept then'accepted'else'declined'end,responded_by=auth.uid(),responded_at=now()where id=c.id;if accept then update public.work_agreements set scope_snapshot=scope_snapshot||E'\n\nAccepted change order: '||c.scope_delta,exchange_snapshot=exchange_snapshot||jsonb_build_object('last_change_cash_delta_cents',c.cash_delta_cents,'last_change_barter_delta',c.barter_delta),version=version+1 where id=a.id;update public.work_issues set status='resolved',resolved_at=now()where id=i.id;insert into public.agreement_history(agreement_id,actor_id,from_status,to_status,note,version)values(a.id,auth.uid(),a.status,a.status,'Accepted change order: '||c.scope_delta,a.version+1);else update public.work_issues set status='open'where id=i.id;end if;end$$;
create or replace function public.manage_work_issue(target_issue_id uuid,issue_action text)returns void language plpgsql security definer set search_path=public as $$declare i public.work_issues;a public.work_agreements;begin select*into i from public.work_issues where id=target_issue_id for update;select*into a from public.work_agreements where id=i.agreement_id for update;if auth.uid()not in(a.requester_id,a.provider_id)then raise exception'agreement participant required';end if;if issue_action='close'then update public.work_issues set status='closed',resolved_at=now()where id=i.id;elsif issue_action='escalate'then update public.work_issues set status='escalated'where id=i.id;update public.work_agreements set status='disputed',version=version+1 where id=a.id;update public.work_requests set stage='disputed',updated_at=now()where id=a.request_id;else raise exception'invalid issue action';end if;end$$;
create or replace function public.add_work_issue_evidence(target_issue_id uuid,asset_path_value text,caption_value text)returns uuid language plpgsql security definer set search_path=public as $$declare i public.work_issues;a public.work_agreements;result uuid;begin select*into i from public.work_issues where id=target_issue_id;select*into a from public.work_agreements where id=i.agreement_id;if auth.uid()not in(a.requester_id,a.provider_id)then raise exception'agreement participant required';end if;insert into public.work_issue_evidence(issue_id,uploaded_by,asset_path,caption)values(i.id,auth.uid(),asset_path_value,trim(caption_value))returning id into result;return result;end$$;
revoke all on function public.get_change_order_hub(uuid),public.report_work_issue(uuid,jsonb),public.propose_change_order(uuid,jsonb),public.respond_change_order(uuid,boolean),public.manage_work_issue(uuid,text),public.add_work_issue_evidence(uuid,text,text)from public;grant execute on function public.get_change_order_hub(uuid),public.report_work_issue(uuid,jsonb),public.propose_change_order(uuid,jsonb),public.respond_change_order(uuid,boolean),public.manage_work_issue(uuid,text),public.add_work_issue_evidence(uuid,text,text)to authenticated;
