alter table public.notifications drop constraint if exists notifications_kind_check;
alter table public.notifications add constraint notifications_kind_check check(kind in('proposal','message','agreement','milestone','hold','obligation','review','system','network'));

create table public.collaboration_invitations(
 id uuid primary key default gen_random_uuid(), sender_id uuid not null references public.profiles(id) on delete cascade,
 recipient_id uuid not null references public.profiles(id) on delete cascade, request_id uuid references public.work_requests(id) on delete set null,
 need_text text not null check(char_length(need_text) between 2 and 500), offer_text text not null check(char_length(offer_text) between 2 and 500),
 note text check(char_length(note)<=1000), status text not null default 'pending' check(status in('pending','accepted','declined','muted')),
 created_at timestamptz not null default now(), responded_at timestamptz, check(sender_id<>recipient_id)
);
create unique index one_pending_invitation on public.collaboration_invitations(sender_id,recipient_id) where status='pending';
create table public.introduction_messages(id uuid primary key default gen_random_uuid(),invitation_id uuid not null references public.collaboration_invitations(id) on delete cascade,author_id uuid not null references public.profiles(id),body text not null check(char_length(body) between 1 and 1500),created_at timestamptz not null default now());
create table public.saved_profiles(owner_id uuid not null references public.profiles(id) on delete cascade,profile_id uuid not null references public.profiles(id) on delete cascade,created_at timestamptz not null default now(),primary key(owner_id,profile_id),check(owner_id<>profile_id));
create table public.saved_searches(id uuid primary key default gen_random_uuid(),owner_id uuid not null references public.profiles(id) on delete cascade,name text not null check(char_length(name) between 2 and 80),query text not null default '',exchange_filter text,remote_only boolean not null default false,created_at timestamptz not null default now());
alter table public.collaboration_invitations enable row level security;alter table public.introduction_messages enable row level security;alter table public.saved_profiles enable row level security;alter table public.saved_searches enable row level security;
create policy "invitation participants read" on public.collaboration_invitations for select using(auth.uid() in(sender_id,recipient_id));
create policy "accepted participants read messages" on public.introduction_messages for select using(exists(select 1 from public.collaboration_invitations i where i.id=invitation_id and i.status='accepted' and auth.uid() in(i.sender_id,i.recipient_id)));
create policy "own saved profiles" on public.saved_profiles for all using(owner_id=auth.uid()) with check(owner_id=auth.uid());
create policy "own saved searches" on public.saved_searches for all using(owner_id=auth.uid()) with check(owner_id=auth.uid());
grant select on public.collaboration_invitations,public.introduction_messages to authenticated;grant select,insert,delete on public.saved_profiles,public.saved_searches to authenticated;

create or replace function public.send_collaboration_invitation(target_profile_id uuid,need_value text,offer_value text,note_value text default null,target_request_id uuid default null) returns uuid language plpgsql security definer set search_path=public as $$declare new_id uuid;begin
 if auth.uid() is null or target_profile_id=auth.uid() then raise exception 'valid signed-in recipient required';end if;
 if exists(select 1 from public.blocks where (blocker_id=target_profile_id and blocked_id=auth.uid()) or (blocker_id=auth.uid() and blocked_id=target_profile_id)) then raise exception 'interaction unavailable';end if;
 insert into public.collaboration_invitations(sender_id,recipient_id,request_id,need_text,offer_text,note) values(auth.uid(),target_profile_id,target_request_id,trim(need_value),trim(offer_value),nullif(trim(note_value),'')) returning id into new_id;
 perform public.notify_user(target_profile_id,'network','New collaboration invitation',(select display_name from public.profiles where id=auth.uid())||' proposed a possible exchange.',target_request_id,null);return new_id;end$$;
create or replace function public.respond_collaboration_invitation(target_invitation_id uuid,response text) returns void language plpgsql security definer set search_path=public as $$declare item public.collaboration_invitations;begin
 if response not in('accepted','declined','muted') then raise exception 'invalid response';end if;select * into item from public.collaboration_invitations where id=target_invitation_id for update;if item.recipient_id<>auth.uid() or item.status<>'pending' then raise exception 'pending recipient invitation required';end if;update public.collaboration_invitations set status=response,responded_at=now() where id=item.id;perform public.notify_user(item.sender_id,'network','Invitation '||response,(select display_name from public.profiles where id=auth.uid())||' '||response||' your collaboration invitation.',item.request_id,null);end$$;
create or replace function public.send_introduction_message(target_invitation_id uuid,message_body text) returns uuid language plpgsql security definer set search_path=public as $$declare new_id uuid;other_id uuid;begin
 select case when sender_id=auth.uid() then recipient_id else sender_id end into other_id from public.collaboration_invitations where id=target_invitation_id and status='accepted' and auth.uid() in(sender_id,recipient_id);if other_id is null then raise exception 'accepted invitation required';end if;insert into public.introduction_messages(invitation_id,author_id,body) values(target_invitation_id,auth.uid(),trim(message_body)) returning id into new_id;perform public.notify_user(other_id,'network','New introduction message',(select display_name from public.profiles where id=auth.uid())||' sent a private message.');return new_id;end$$;
create or replace function public.get_network_inbox() returns jsonb language sql stable security definer set search_path=public as $$select jsonb_build_object('invitations',coalesce((select jsonb_agg((to_jsonb(i)||jsonb_build_object('sender_name',s.display_name,'recipient_name',r.display_name)) order by i.created_at desc) from public.collaboration_invitations i join public.profiles s on s.id=i.sender_id join public.profiles r on r.id=i.recipient_id where auth.uid() in(i.sender_id,i.recipient_id)),'[]'::jsonb),'messages',coalesce((select jsonb_agg((to_jsonb(m)||jsonb_build_object('author_name',p.display_name)) order by m.created_at) from public.introduction_messages m join public.profiles p on p.id=m.author_id join public.collaboration_invitations i on i.id=m.invitation_id where i.status='accepted' and auth.uid() in(i.sender_id,i.recipient_id)),'[]'::jsonb),'saved_profiles',coalesce((select jsonb_agg(profile_id) from public.saved_profiles where owner_id=auth.uid()),'[]'::jsonb),'saved_searches',coalesce((select jsonb_agg(to_jsonb(x) order by created_at desc) from public.saved_searches x where owner_id=auth.uid()),'[]'::jsonb))$$;
create or replace function public.set_saved_profile(target_profile_id uuid,should_save boolean) returns void language plpgsql security definer set search_path=public as $$begin if should_save then insert into public.saved_profiles(owner_id,profile_id) values(auth.uid(),target_profile_id) on conflict do nothing;else delete from public.saved_profiles where owner_id=auth.uid() and profile_id=target_profile_id;end if;end$$;
create or replace function public.save_network_search(search_name text,search_query text,exchange_value text,remote_value boolean) returns uuid language plpgsql security definer set search_path=public as $$declare new_id uuid;begin insert into public.saved_searches(owner_id,name,query,exchange_filter,remote_only) values(auth.uid(),trim(search_name),coalesce(search_query,''),nullif(exchange_value,''),remote_value) returning id into new_id;return new_id;end$$;
revoke all on function public.send_collaboration_invitation(uuid,text,text,text,uuid),public.respond_collaboration_invitation(uuid,text),public.send_introduction_message(uuid,text),public.get_network_inbox(),public.set_saved_profile(uuid,boolean),public.save_network_search(text,text,text,boolean) from public;
grant execute on function public.send_collaboration_invitation(uuid,text,text,text,uuid),public.respond_collaboration_invitation(uuid,text),public.send_introduction_message(uuid,text),public.get_network_inbox(),public.set_saved_profile(uuid,boolean),public.save_network_search(text,text,text,boolean) to authenticated;

create or replace function public.get_network_activity(following_only boolean default false) returns table(activity jsonb) language sql stable security definer set search_path=public as $$select activity from(
 select jsonb_build_object('kind','portfolio','at',pe.published_at,'profile_id',pe.profile_id,'name',p.display_name,'title',pe.title,'summary',pe.summary,'entry_id',pe.id) activity from public.portfolio_entries pe join public.profiles p on p.id=pe.profile_id where pe.visibility='public' and p.is_active and(not following_only or exists(select 1 from public.follows f where f.follower_id=auth.uid() and f.followed_profile_id=pe.profile_id))
 union all select jsonb_build_object('kind','request','at',r.created_at,'profile_id',r.owner_id,'name',p.display_name,'title',r.title,'summary',r.description,'request_id',r.id) from public.work_requests r join public.profiles p on p.id=r.owner_id where r.stage='open' and r.visibility='public' and p.is_active and(not following_only or exists(select 1 from public.follows f where f.follower_id=auth.uid() and f.followed_profile_id=r.owner_id))) x order by(activity->>'at')::timestamptz desc limit 50$$;
grant execute on function public.get_network_activity(boolean) to anon,authenticated;
