alter table public.profiles add column work_radius_km integer check(work_radius_km between 0 and 1000);
alter table public.profiles add column remote_available boolean not null default false;
alter table public.profiles add column preferred_exchange_modes public.exchange_mode[] not null default array['cash','barter','hybrid']::public.exchange_mode[];
alter table public.profiles add column availability_text text;
alter table public.profiles add column resources_text text;
alter table public.profiles add column profile_visibility text not null default 'public' check(profile_visibility in('public','members','private'));

create table public.portfolio_entries(id uuid primary key default gen_random_uuid(),agreement_id uuid not null references public.work_agreements(id) on delete cascade,profile_id uuid not null references public.profiles(id),title text not null,summary text not null,visibility text not null default 'public' check(visibility in('public','members','private')),published_at timestamptz not null default now(),unique(agreement_id,profile_id));
alter table public.portfolio_entries enable row level security;grant select,insert,update,delete on public.portfolio_entries to authenticated,anon;
create policy "visible portfolio readable" on public.portfolio_entries for select using(visibility='public' or profile_id=auth.uid());
create policy "completed participant manages portfolio" on public.portfolio_entries for all using(profile_id=auth.uid()) with check(profile_id=auth.uid() and exists(select 1 from public.work_agreements a where a.id=agreement_id and a.status='completed' and auth.uid() in(a.requester_id,a.provider_id)));

create table public.completion_summaries(id uuid primary key default gen_random_uuid(),agreement_id uuid not null unique references public.work_agreements(id) on delete cascade,summary text not null,exchange_breakdown jsonb not null default '[]'::jsonb,submitted_by uuid not null references public.profiles(id),created_at timestamptz not null default now());
alter table public.completion_summaries enable row level security;grant select,insert on public.completion_summaries to authenticated;
create policy "participants read completion" on public.completion_summaries for select using(exists(select 1 from public.work_agreements a where a.id=agreement_id and auth.uid() in(a.requester_id,a.provider_id)));
create policy "completed participant adds summary" on public.completion_summaries for insert with check(submitted_by=auth.uid() and exists(select 1 from public.work_agreements a where a.id=agreement_id and a.status='completed' and auth.uid() in(a.requester_id,a.provider_id)));

create or replace function public.set_my_profile(payload jsonb) returns public.profiles language plpgsql security definer set search_path=public as $$ declare result public.profiles;begin if auth.uid() is null then raise exception 'authentication required';end if;update public.profiles set display_name=trim(payload->>'display_name'),location_text=nullif(trim(payload->>'location_text'),''),bio=nullif(trim(payload->>'bio'),''),work_radius_km=nullif(payload->>'work_radius_km','')::integer,remote_available=coalesce((payload->>'remote_available')::boolean,remote_available),preferred_exchange_modes=coalesce(array(select jsonb_array_elements_text(payload->'preferred_exchange_modes')::public.exchange_mode),preferred_exchange_modes),availability_text=nullif(trim(payload->>'availability_text'),''),resources_text=nullif(trim(payload->>'resources_text'),''),profile_visibility=coalesce(nullif(payload->>'profile_visibility',''),profile_visibility) where id=auth.uid() returning * into result;
 if jsonb_typeof(payload->'needs')='array' then delete from public.capabilities where profile_id=auth.uid() and direction='need';insert into public.capabilities(profile_id,direction,label) select auth.uid(),'need',trim(value) from jsonb_array_elements_text(payload->'needs') where char_length(trim(value)) between 2 and 100;end if;if jsonb_typeof(payload->'offers')='array' then delete from public.capabilities where profile_id=auth.uid() and direction='offer';insert into public.capabilities(profile_id,direction,label) select auth.uid(),'offer',trim(value) from jsonb_array_elements_text(payload->'offers') where char_length(trim(value)) between 2 and 100;end if;return result;end $$;
